# Generated by Django 3.1.7 on 2021-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20210805_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_history',
            name='receiveraccno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer_history',
            name='senderaccno',
            field=models.IntegerField(default=0),
        ),
    ]
